import Head from 'next/head'
import Link from 'next/link'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MenuCard from '../components/Card'
import MenuCardSanpo from '../components/CardMenu'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <h1>Taylorちゃんの記録</h1>  
        </div>        
        <div className='d-flex mt-5'>
          <div className='me-5'>
            <MenuCard></MenuCard>
          </div>
          <div>
            <MenuCardSanpo></MenuCardSanpo>
          </div>
        </div>
      </main>
    </div>
  )
}
